AWSTemplateFormatVersion: '2010-09-09'

Description: Staging Environment for Cloud Native App

Resources:

  StagingBucket:
    Type: AWS::S3::Bucket

    Properties:
      BucketName: !Sub "taskapp-staging-${AWS::AccountId}-${AWS::Region}"

      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html

      VersioningConfiguration:
        Status: Enabled

      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        IgnorePublicAcls: false
        BlockPublicPolicy: false
        RestrictPublicBuckets: false

  BucketPolicy:
    Type: AWS::S3::BucketPolicy

    Properties:
      Bucket: !Ref StagingBucket

      PolicyDocument:
        Version: "2012-10-17"

        Statement:
          - Effect: Allow

            Principal: "*"

            Action:
              - s3:GetObject

            Resource:
              - !Sub "${StagingBucket.Arn}/*"

Outputs:

  BucketName:
    Value: !Ref StagingBucket

  WebsiteURL:
    Value: !GetAtt StagingBucket.WebsiteURL